name = "atto"
version = "1.2.0"
description = "Robust and extensible parser combinators for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "ieeemma", repo = "atto" }

[documentation]
pages = [
    { title = "Quickstart guide", path = "quickstart.html", source = "./docs/quick-start.md" },
    { title = "Advanced use", path = "Advanced.html", source = "./docs/advanced-use.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
