name = "glide"
version = "1.0.0"
description = "Robust and extensible parser combinators for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "ieeemma", repo = "glide" }

[documentation]
pages = [
    { title = "Quickstart guide", path = "quickstart.html", source = "./docs/quick-start.md" },
    { title = "Advanced use", path = "Advanced.html", source = "./docs/advanced-use.md" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
